export POSTGRES_USER=leads_manager_bot
export POSTGRES_PASSWORD=password
export POSTGRES_DB=leads_manager_bot
export POSTGRES_HOST=localhost
export POSTGRES_PORT=5432
export DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
export TELEGRAM_BOT_TOKEN=1234567890:ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890